### PR TITLE
Fix logic for `isPristine`

### LINKED ISSUE #101: Do not register a change when current "model.value" equals current "changeset.value"
I am totally in love with ember-changeset! Bravo!

I have this finding:

Given an empty changeset field in a template, e.g. {input type="text" value=changeset.familyName}}. 

Via `controller.set('changeset', new Changeset(model))` this changeset is bound to a newly created `person` record. 

Problem: ember-changeset registers a change after entering this empty field and leaving the field untouched.

Enhancement request: Do not do that!

This request probably could be replaced by a more generic enhancement request: **Do not make or keep a change registration (in changeset.changes), when current "model.value" equals current  "changeset.value"**.

### PR DESCRIPTION
**Pull request by poteto**
A changeset is pristine if and only if all changes are present and
equal to values on the underlying content

Closes #101

### CODE REVIEW

**Comment by Keeo** [comment]
Looking forward to see this released. :+1:

**Comment by sukima** [comment]
Just an FYI. This one PR is blocking us from using this addon. We had to reinvent the changeset. Anxiously waiting for this to clean up our code.

**Comment by poteto** [comment]
@sukima Will get this merged / released today

**Comment by poteto** [comment]
Released in `1.1.4`

**Pull request merged**
