### PR TITLE
Make `isChangeset` a public method (#146)

### PR DESCRIPTION
**Pull request by ironkeith**
This should be a non-breaking change moving forward.

No stress if you're not into this direction, I just thought I'd make it as easy as possible if you were!

### CODE REVIEW

**Comment by poteto** [comment]
Thanks! Could you update the readme as well please?

**Comment by ironkeith** [comment]
@poteto I took a crack at updating the README. Let me know if that's cool, or if you'd like me to elaborate further.

**Comment by poteto** [comment]
Thanks!

**Comment by ironkeith** [comment]
Thank you @poteto! 🙌

**Pull request merged**
