### PR TITLE
Update test to verify property update

### LINKED ISSUE #49: property not notified when using a validator
I am getting the bug fixed in #47 when i pass a validator (either as an action or an ember-changeset-validators validation map).

```hbs
{{#with (changeset model (action "validate") as |changeset|}}
  <h2>{{changeset.email}}</h2>
  <input value={{changeset.email}} oninput={{action (mut changeset.email) value="target.value"}}>
{{/with}}
```

### PR DESCRIPTION
**Pull request by poteto**
Closes #49

### CODE REVIEW

**Comment by poteto** [comment]
@dustinfarris I have added tests for both with and without a validator function, and it seems to still be updating. I think your issue might be something else.

**Comment by dustinfarris** [comment]
Update the validator in your test to return `false` and see if it still passes.

**Comment by dustinfarris** [comment]
@poteto aha, that would be it then.  so i still have an issue in ember-paper where the paper-input matches the `value` property exactly.

**Comment by poteto** [comment]
Sounds like the issue should be opened on ember-paper then! We have fixed the bug on our end, so I will close #49 once I merge this in.

**Comment by dustinfarris** [comment]
Yes indeed.  Thanks for your support.

**Comment by miguelcobain** [comment]
Isn't it strange to have:
```
> changeset.get('email')
undefined
> changeset.set('email', 'dustin')
"dustin"
> changeset.get('email')
undefined
```
?

The set itself returned the value, but then a get doesn't.
From the perspective of a component, it should always represent `email`. If it is `undefined`, I just show `undefined`?
What am I missing here?

**Pull request merged**
