### PR TITLE
Key detection that works for Ember Objects

### PR DESCRIPTION
**Pull request by demersus**
I'm not sure if this is the direction you were wanting to go, but this fixes the problem for ember objects.

See: https://github.com/DockYard/ember-changeset/issues/153

### CODE REVIEW

**Comment by poteto** [comment]
@gordonbisnor can you give this a try and let me know if it fixes the issue for you?

**Comment by gordonbisnor** [comment]
@poteto ha yes I had already done pull request #151 with the same change, so in my opinion this works.

**Comment by poteto** [comment]
Ah my bad, I completely missed that. Closing this in favor of #151.

**Comment by gordonbisnor** [comment]
Ha no worries thanks for the update!

**Pull request closed without merging**
