### PR TITLE
Bringing feature branch up to date with master.

### PR DESCRIPTION
**Pull request by webark**

### CODE REVIEW

**Comment by webark** [comment]
@poteto I feel like I got everything in this merge. Here is a diff with where my final changes are at for #140 that I'd like to bring in. Thought that the bringing the feature branch up to date with master should be handled in a sperate PR. But the merge commit I had to do was.. more than I'd thought. So let me know if I should try to redo it, or if you or someone else wants to do the merge before I setup a PR to merge my version of the nested changes. https://github.com/webark/ember-changeset/compare/feature/support-nested-keys...webark:feature/support-nested-keys_keyd-changes?expand=1

**Comment by webark** [comment]
Cleaned up the merge commit a bit, so it's looking better now.

**Comment by poteto** [comment]
@webark This is hard to compare, so I'm going to merge this into the feature branch and then verify again there that the merge was done right

**Comment by webark** [comment]
@poteto gosh.. I don't see why things are so confused with this branch. :/ Like if I go to https://github.com/DockYard/ember-changeset/compare/feature/support-nested-keys...webark:feature/support-nested-keys_keyd-changes?expand=1 It says I'm changing the `ecmaVersion: 6,` to `ecmaVersion: 2017,` .. but if I just go to both branches, they both say 2017.. :/

**Pull request merged**
